dist: xenial
language: node_js
node_js: node

cache:
  directories:
    - node_modules

# will run `npm install` automatically here

script:
  - npm test
  - npm run build

notifications:
  email: false
